//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeExtensions.WorkingDays {
    using System;
    using System.Diagnostics;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HolidayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal HolidayNames() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DateTimeExtensions.WorkingDays.HolidayNames", typeof(HolidayNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All Saints.
        /// </summary>
        public static string AllSaints {
            get {
                return ResourceManager.GetString("AllSaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Assumption.
        /// </summary>
        public static string Assumption {
            get {
                return ResourceManager.GetString("Assumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Carnival.
        /// </summary>
        public static string Carnival {
            get {
                return ResourceManager.GetString("Carnival", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Christmas.
        /// </summary>
        public static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Christmas Eve.
        /// </summary>
        public static string ChristmasEve {
            get {
                return ResourceManager.GetString("ChristmasEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Corpus Christi.
        /// </summary>
        public static string CorpusChristi {
            get {
                return ResourceManager.GetString("CorpusChristi", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Day of the Dead.
        /// </summary>
        public static string DayOfTheDead {
            get {
                return ResourceManager.GetString("DayOfTheDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Easter.
        /// </summary>
        public static string Easter {
            get {
                return ResourceManager.GetString("Easter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Easter Monday.
        /// </summary>
        public static string EasterMonday {
            get {
                return ResourceManager.GetString("EasterMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Easter Saturday.
        /// </summary>
        public static string EasterSaturday {
            get {
                return ResourceManager.GetString("EasterSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Epiphany.
        /// </summary>
        public static string Epiphany {
            get {
                return ResourceManager.GetString("Epiphany", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Constitution Day.
        /// </summary>
        public static string Espanha_ConstitutionDay {
            get {
                return ResourceManager.GetString("Espanha_ConstitutionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to National Day.
        /// </summary>
        public static string Espanha_NationalDay {
            get {
                return ResourceManager.GetString("Espanha_NationalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to German Unity Day.
        /// </summary>
        public static string GermanUnityDay {
            get {
                return ResourceManager.GetString("GermanUnityDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Good Friday.
        /// </summary>
        public static string GoodFriday {
            get {
                return ResourceManager.GetString("GoodFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Imaculate Conception.
        /// </summary>
        public static string ImaculateConception {
            get {
                return ResourceManager.GetString("ImaculateConception", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Independance Day.
        /// </summary>
        public static string IndependanceDay {
            get {
                return ResourceManager.GetString("IndependanceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to International Workers&apos; day.
        /// </summary>
        public static string InternationalWorkerDay {
            get {
                return ResourceManager.GetString("InternationalWorkerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Maundy Thursday.
        /// </summary>
        public static string MaundyThursday {
            get {
                return ResourceManager.GetString("MaundyThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to May Day.
        /// </summary>
        public static string MayDay {
            get {
                return ResourceManager.GetString("MayDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New Year.
        /// </summary>
        public static string NewYear {
            get {
                return ResourceManager.GetString("NewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Our Lady of Aparecida.
        /// </summary>
        public static string OurLadyOfAparecida {
            get {
                return ResourceManager.GetString("OurLadyOfAparecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Palm Sunday.
        /// </summary>
        public static string PalmSunday {
            get {
                return ResourceManager.GetString("PalmSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pentecost.
        /// </summary>
        public static string Pentecost {
            get {
                return ResourceManager.GetString("Pentecost", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pentecost Monday.
        /// </summary>
        public static string PentecostMonday {
            get {
                return ResourceManager.GetString("PentecostMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Freedom Day.
        /// </summary>
        public static string Portugal_FreedomDay {
            get {
                return ResourceManager.GetString("Portugal_FreedomDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Portugal Day.
        /// </summary>
        public static string Portugal_PortugalDay {
            get {
                return ResourceManager.GetString("Portugal_PortugalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Republic Day.
        /// </summary>
        public static string Portugal_RepublicDay {
            get {
                return ResourceManager.GetString("Portugal_RepublicDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Restoration of Independance.
        /// </summary>
        public static string Portugal_RestorationIndependance {
            get {
                return ResourceManager.GetString("Portugal_RestorationIndependance", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Republic Day.
        /// </summary>
        public static string RepublicDay {
            get {
                return ResourceManager.GetString("RepublicDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to St Stephen&apos;s Day.
        /// </summary>
        public static string StStephenDay {
            get {
                return ResourceManager.GetString("StStephenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tiradentes Day.
        /// </summary>
        public static string TiradentesDay {
            get {
                return ResourceManager.GetString("TiradentesDay", resourceCulture);
            }
        }
    }
}
