// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("DateTimeExtensions")]
[assembly: AssemblyDescriptionAttribute("Merge of extensions for System.DateTime like localized working days with holidays calculations and natural time date difference")]
[assembly: AssemblyProductAttribute("DateTimeExtensions")]
[assembly: AssemblyVersionAttribute("3.9.0.0")]
[assembly: AssemblyFileVersionAttribute("3.9.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.9.0.0";
    }
}
